title: Ernst.site
logo: 
description: <br>Varsity Student Athlete at Lehigh University <br><br> Electrical Engineering and German Major
 <br><br> Please See - www.ernst.lighting
show_downloads: FALSE
google_analytics: 
google_analytics: 
theme: jekyll-theme-minimal
